server:
  port: 8089

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://114.132.201.144:3306/vpn?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: KangoShyVpn500-mysql
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://114.132.201.144:3306/vpn?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: KangoShyVpn500-mysql

  redis:
    host: 114.132.201.144
    port: 6379
    password: KangoShyVpn500-redis


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mvc:
    static-path-pattern: /static/**

  rabbitmq:
    host: 114.132.201.144
    port: 5672
    username: admin
    password: KangoShyVpn500-rabbitmq
    connection-timeout: 5000
    ssl:
      enabled: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0